spring:
  datasource:
    # database url
    url: "jdbc:mysql://127.0.0.1:3306/cloud_storage_disk?useSSL=false&\
      useUnicode=true&\
      characterEncoding=UTF-8&\
      allowMultiQueries=true&\
      allowPublicKeyRetrieval=true&\
      serverTimezone"
    # username and password of database
    username: root
    password: Jhxz951129Jhxz
  # redis config
  redis:
    host: 127.0.0.1
    password: 123456
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl